In [1]:
import pandas as pd
from utils import prepare_data
from interpolate import simple_interpolate
from dataset import FinedustDataset

region = "Andong"
df = prepare_data(region.lower())
df = simple_interpolate(df)
dataset = FinedustDataset(df)

/home/han07301/ai_project/JH/LSTM/interpolate.py:41: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data = data.interpolate(method='linear')
/home/han07301/ai_project/JH/LSTM/interpolate.py:41: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data = data.interpolate(method='linear')

In [2]:
df

,TM,STN,WD,WS,PA,PS,TA,TD,HM,PV,...,TD_dalian,HM_dalian,PS_dalian,PT_dalian,PR_dalian,RH_dalian,PM10_dalian,LON_dalian,LAT_dalian,diff
0,2018-01-01 00:00:00,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-9.2,52.1,1028.3,2.0,1.6,0.0,49.0,121.63,38.9,NaN
1,2018-01-01 03:00:00,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-10.1,42.9,1028.9,2.0,0.6,0.0,94.0,121.63,38.9,3.0
2,2018-01-01 06:00:00,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-10.1,42.9,1028.9,2.0,0.6,0.0,94.0,121.63,38.9,3.0
3,2018-01-01 09:00:00,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-17.6,25.0,1027.6,2.0,0.2,0.0,120.0,121.63,38.9,3.0
4,2018-01-01 12:00:00,136.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-16.3,31.1,1029.1,2.0,1.4,0.0,30.0,121.63,38.9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9679,2022-09-07 03:00:00,136.0,29.0,1.2,997.1,1013.5,17.7,14.1,80.0,16.1,...,15.2,56.2,1016.8,2.0,2.0,2.0,29.0,121.63,38.9,3.0
9680,2022-09-07 06:00:00,136.0,0.0,0.2,1000.2,1017.0,13.6,12.8,95.0,14.8,...,6.8,24.0,1016.6,7.0,0.8,2.0,21.0,121.63,38.9,3.0
9681,2022-09-07 09:00:00,136.0,18.0,0.8,1002.0,1018.5,19.8,15.2,75.0,17.3,...,14.3,44.1,1016.9,2.0,0.2,2.0,4.0,121.63,38.9,3.0
9682,2022-09-07 12:00:00,136.0,27.0,1.2,1001.5,1017.7,24.8,15.4,56.0,17.5,...,15.9,65.9,1018.3,2.0,1.4,2.0,13.0,121.63,38.9,3.0
9683,2022-09-07 15:00:00,136.0,27.0,2.6,1000.3,1016.3,27.0,14.0,45.0,16.0,...,12.3,56.1,1018.8,2.0,0.5,2.0,6.0,121.63,38.9,3.0

In [4]:
correlation_matrix = df[dataset.feature_columns].corr()

# 상관관계가 높은 feature 선택 (예: 0.5 이상의 상관관계)
significant_features = correlation_matrix[correlation_matrix.abs() > 0.5].index.tolist()

# 유의미한 feature로 새로운 데이터프레임 생성
df_significant = df[significant_features]

# 결과 출력
print(df_significant)

        STN    WD   WS      PA      PS    TA    TD    HM    PV  CA_TOT  ...  \
0     136.0   0.0  0.0     0.0     0.0   0.0   0.0   0.0   0.0     0.0  ...
1     136.0   0.0  0.0     0.0     0.0   0.0   0.0   0.0   0.0     0.0  ...
2     136.0   0.0  0.0     0.0     0.0   0.0   0.0   0.0   0.0     0.0  ...
3     136.0   0.0  0.0     0.0     0.0   0.0   0.0   0.0   0.0     0.0  ...
4     136.0   0.0  0.0     0.0     0.0   0.0   0.0   0.0   0.0     0.0  ...
...     ...   ...  ...     ...     ...   ...   ...   ...   ...     ...  ...
9679  136.0  29.0  1.2   997.1  1013.5  17.7  14.1  80.0  16.1     0.0  ...
9680  136.0   0.0  0.2  1000.2  1017.0  13.6  12.8  95.0  14.8     5.0  ...
9681  136.0  18.0  0.8  1002.0  1018.5  19.8  15.2  75.0  17.3     2.0  ...
9682  136.0  27.0  1.2  1001.5  1017.7  24.8  15.4  56.0  17.5     0.0  ...
9683  136.0  27.0  2.6  1000.3  1016.3  27.0  14.0  45.0  16.0     0.0  ...

      TD_dalian  HM_dalian  PS_dalian  PT_dalian  PR_dalian  RH_dalian  \
0          -9.2       52.1     1028.3        2.0        1.6        0.0
1         -10.1       42.9     1028.9        2.0        0.6        0.0
2         -10.1       42.9     1028.9        2.0        0.6        0.0
3         -17.6       25.0     1027.6        2.0        0.2        0.0
4         -16.3       31.1     1029.1        2.0        1.4        0.0
...         ...        ...        ...        ...        ...        ...
9679       15.2       56.2     1016.8        2.0        2.0        2.0
9680        6.8       24.0     1016.6        7.0        0.8        2.0
9681       14.3       44.1     1016.9        2.0        0.2        2.0
9682       15.9       65.9     1018.3        2.0        1.4        2.0
9683       12.3       56.1     1018.8        2.0        0.5        2.0

      PM10_dalian  LON_dalian  LAT_dalian  diff
0            49.0      121.63        38.9   NaN
1            94.0      121.63        38.9   3.0
2            94.0      121.63        38.9   3.0
3           120.0      121.63        38.9   3.0
4            30.0      121.63        38.9   3.0
...           ...         ...         ...   ...
9679         29.0      121.63        38.9   3.0
9680         21.0      121.63        38.9   3.0
9681          4.0      121.63        38.9   3.0
9682         13.0      121.63        38.9   3.0
9683          6.0      121.63        38.9   3.0

[9684 rows x 103 columns]